--- DO NOT EDIT THIS FILE
--- Generated by DorsalVR 2.0.5
--- This file, and workspace.code-workspace, are required to make Visual Studio Code's IntelliSense work for DorsalVR's Lua scripting.
--- See: https://github.com/MichaelJW/DorsalVR

--- @class DolphinManager
--- This manages Dolphin.
DolphinManager={};
--- @param exePath string
--- @param configDir string
--- Launches a new instance of Dolphin.
function DolphinManager:Launch(exePath, configDir) end
