--- DO NOT EDIT THIS FILE
--- Generated by DorsalVR 2.0.5
--- This file, and workspace.code-workspace, are required to make Visual Studio Code's IntelliSense work for DorsalVR's Lua scripting.
--- See: https://github.com/MichaelJW/DorsalVR

--- @class VRGO
local VRGO_def = {}
--- @param x number
--- @param y number
--- @param z number
function VRGO_def:SetPositionOffset(x, y, z) end
function VRGO_def:ResetPositionOffset() end
--- @param x number
--- @param y number
--- @param z number
function VRGO_def:SetScale(x, y, z) end
function VRGO_def:ResetScale() end
--- @param x number
--- @param y number
--- @param z number
function VRGO_def:SetRotationOffset(x, y, z) end
function VRGO_def:ResetRotationOffset() end
--- @param path string
--- @param interactions string
--- @param processors string
function VRGO_def:SetPositionBinding(path, interactions, processors) end
function VRGO_def:ResetPositionBinding() end
--- @param path string
--- @param interactions string
--- @param processors string
function VRGO_def:SetRotationBinding(path, interactions, processors) end

--- @class DolphinManager
--- This manages Dolphin.
local DolphinManager_def = {}
--- @param dolphinConfig DolphinConfig
--- Launches a new instance of Dolphin.
function DolphinManager_def:Launch(dolphinConfig) end
--- @return DolphinConfig
function DolphinManager_def:CreateDolphinConfig() end

--- @class DeviceManager
--- Allows creation of Dorsal devices
local DeviceManager_def = {}
--- @return Screen
function DeviceManager_def:CreateScreen() end

--- @class Screen
local Screen_def = {}
function Screen_def:EnableSBS3D() end
function Screen_def:DisableSBS3D() end
--- @param x number
--- @param y number
--- @param z number
function Screen_def:SetPositionOffset(x, y, z) end
function Screen_def:ResetPositionOffset() end
--- @param x number
--- @param y number
--- @param z number
function Screen_def:SetScale(x, y, z) end
function Screen_def:ResetScale() end
--- @param x number
--- @param y number
--- @param z number
function Screen_def:SetRotationOffset(x, y, z) end
function Screen_def:ResetRotationOffset() end
--- @param path string
--- @param interactions string
--- @param processors string
function Screen_def:SetPositionBinding(path, interactions, processors) end
function Screen_def:ResetPositionBinding() end
--- @param path string
--- @param interactions string
--- @param processors string
function Screen_def:SetRotationBinding(path, interactions, processors) end

--- @class DolphinConfig
--- @field configDir string
--- @field outputGameTo table<number, string>
--- @field exec string
--- @field videoBackend string
--- @field audioEmulation string
--- @field movie string
--- @field user string
--- @field nandTitle string
--- @field saveState string
--- @field extension string
--- @field gameScreen Screen
--- @field exePath string
local DolphinConfig_def = {}
--- @return DolphinConfig
function DolphinConfig_def:Clone() end
--- @return string
function DolphinConfig_def:ToString() end
--- @param systemSectionKey string
--- @param value string
--- Sets a configuration option as specified by a --config or -C command line option
function DolphinConfig_def:SetConfigOption(systemSectionKey, value) end
--- @param systemSectionKey string
--- Clears a configuration option as specified by a --config or -C command line option
function DolphinConfig_def:ClearConfigOption(systemSectionKey) end
--- Clears all configuration options specified by a --config or -C command line option
function DolphinConfig_def:ClearAllConfigOptions() end

--- Define the objects that are always created by DorsalVR and therefore already accessible:
--- @type DolphinManager
dolphinManager = {}
--- @type DeviceManager
deviceManager = {}
